name: Run Crawling

on:
  schedule:
    - cron: "0 0 * * *" # (UTC 기준) 한국시간기준 오전11시  // 0 0 * * * ==> 한국 9시
  workflow_dispatch: # 수동 실행을 원할 때 사용할 수 있음

jobs:
  api-request-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies and update SSL certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          sudo update-ca-certificates
          python -m pip install --upgrade pip
          pip install requests
          pip install gspread
          pip install oauth2client
          pip install pytz

      - name: Create JSON key file from secret
        run: echo "${{ secrets.JSON_RAWDATA }}" > ./cowithone-scrap-1686123588417-7ea5acec3d36.json

      - name: Set environment variables
        run: |
          echo "JSON_KEYFILE=${{ secrets.JSON_KEYFILE }}" >> $GITHUB_ENV
          echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "API_KEY2=${{ secrets.API_KEY2 }}" >> $GITHUB_ENV
          echo "SLACK_WEBHOOK_NARA_URL=${{ secrets.SLACK_WEBHOOK_NARA_URL }}" >> $GITHUB_ENV
          echo "SLACK_WEBHOOK_NAVER_URL=${{ secrets.SLACK_WEBHOOK_NAVER_URL }}" >> $GITHUB_ENV
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Run main.py
        run: python main.py # API 요청을 할 Python 스크립트 실행
